logging:
    level:
        com:
            jameszmapepa:
                zsestockpriceapi: DEBUG
        org:
            springframework:
                web: DEBUG
spring:
    datasource:
        hikari:
            maximum-pool-size: 5
            minimum-idle: 7
        password: 42;FckMxc
        url: jdbc:mysql://localhost:3306/zse_stock_price?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&TimeZone=CAT
        username: jmapepa
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            org:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

