logging:
    level:
        com:
            jameszmapepa:
                zsestockpriceapi: DEBUG
        org:
            springframework:
                web: DEBUG
spring:
    datasource:
        hikari:
            maximum-pool-size: 5
            minimum-idle: 7
        password: P@ssw0rd
        url: jdbc:postgresql://localhost:5432/zse_stock_price?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&TimeZone=CAT
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            org:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

