logging:
    level:
        com:
            jameszmapepa:
                zsestockpriceapi: DEBUG
        org:
            springframework:
                web: DEBUG
spring:
    datasource:
        hikari:
            maximum-pool-size: 5
            minimum-idle: 7
        password: 8eb55359484e720ed7be99a707e20589e10b5e3cb619a5ce1744d0520f005203
        url: jdbc:postgresql://ec2-54-155-35-88.eu-west-1.compute.amazonaws.com:5432/d70nql85qki6b?autoReconnect=true&createDatabaseIfNotExist=true&sslmode=require&TimeZone=CAT
        username: klurdllrfiechd
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            org:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
